name: CMake Build Matrix

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Configure
      run: cmake .

    - name: Build
      run: make

    - name: Run tests
      run: make test
